// riddledata.js — Riddle list for MyRiddlePage
// Each riddle: { id, name, difficulty, lines, hints, answer }

const RIDDLES = [
  {
    id: 1,
    name: "It was left there, it is part here",
    difficulty: "moderate",
    lines: [
      "They found 'it' buried, but still left 'it',",
      "and just took what was present in 'it'.",
      "For them, of course, was just the treasure,",
      "which they sought for life-long money and pleasure.",
      "'It' is also present on the tree,",
      "a part of most cars, I've seen.",
      "'It' is part of both elephant and you,",
      "guess the 'it', you've got every clue.",
    ],
    hints: [
      "The same word refers to a body part, a treasure holder, and a vehicle compartment.",
      "Think of something shared by an elephant, a tree, and many cars.",
    ],
    answer: "trunk",
    
  },
  {
    id: 2,
    name: "Can see or not?",
    difficulty: "moderate",
    lines: [
      "Whenever 'it' is there, I am able to see,",
      "Still 'it' is what I'm sure, you can't ever see.",
      "'It' is neither heavy, nor does 'it' take space,",
      "Wherever you are, whatever is your place.",
      "Yet 'it' fills up the room, you were in before,",
      "'It' never makes a sound, it's a fact, I'm sure.",
      "'It' is no doubt, essential, for me and for you,",
      "But still we don't save 'it', and you can't do that too!",
      "If you are 'it', then you should eat and eat,",
      "Find the 'it', though for this, you won't get a treat.",
    ],
    hints: [
      "no sound, no space, necessary but can't save. hmm.",
      "You rely on 'it' every day, but 'it' isn't something you can physically hold.",
    ],
    answer: "light",
    
  },
  {
    id: 3,
    name: "Faces of Fortune",
    difficulty: "easy",
    lines: [
      "I threw 'it', you threw 'it', but 'it' is not a waste,",
      "'It' can help me or make me lose, according to 'its' face.",
      "'It' has many faces, but I assure you, 'it' is not the Ravanna,",
      "'It' has many dots, just like bullets, but 'it' is not a gun.",
      "'It' helped me reach the ladder, 'it' made me overtake others,",
      "Find the 'it', it's not that hard, my fellow sisters and brothers.",
    ],
    hints: ["Board games often can't begin without 'it'.", "Its outcome depends entirely on which face lands upward."],
    answer: ["dice", "die"],
    
  },
  {
    id: 4,
    name: "The Final Visitor",
    difficulty: "easy",
    lines: [
      "'It' is something you have never got, neither have you experienced,",
      "But still I'm sure, a day will come, when you'll become 'its' recipient.",
      "I would never want you to, experience 'it' so soon,",
      "as for if you get 'it', my riddles would be read by whom?",
      "'It' is for everyone, it's a rule, that 'it' will come to visit,",
      "and, you well know you will get 'it', it's enough, so guess the 'it'.",
    ],
    hints: ["It's the one certainty shared by everyone.", "Every living being is destined to encounter 'it' once."],
    answer: "death",
    
  },
  {
    id: 5,
    name: "A Well-Placed Serve",
    difficulty: "tough",
    lines: [
      "'It' is not to be eaten, but yet is what we serve,",
      "I hit 'it', you do that too, and 'it' goes in a curve.",
      "If I do never hit 'it', that is called love usually,",
      "But still my mother says - hit 'it', do not be so silly!",
      "If I serve, and 'it' is for you,",
      "then I would never want you to-",
      "return 'it', so that I get praised,",
      "find the 'it', if this is the case.",
    ],
    hints: [
      "The clue 'love' not means the relation and liking here.",
      "Different sports use different versions, but they all serve 'it'.",
    ],
    answer: ["shuttlecock", "tennis ball", "table tennis ball"],
    
  },
  {
    id: 6,
    name: "The Used Hero",
    difficulty: "easy",
    lines: [
      "I used 'him' for a purpose, oh sorry,",
      "'It' was for my own greed,",
      "'He' is trapped in the plan now, 'he' can't escape,",
      "I don't care if he was with me,",
      "I sacrificed 'it' for the king and king's horses,",
      "For 'it' was for me most worthless,",
      "But if 'it' reaches the end, 'it' would be,",
      "For me and my side, the best.",
      "'It' is a thing, 'he' is someone, yet they both are same,",
      "if you can't find the him or 'it', 'it' would be a shame.",
    ],
    hints: [
      "He and it are two different meaning of the same answer.",
      "It begins as the least valuable piece on the board.",
    ],
    answer: "pawn",
    
  },
  {
    id: 7,
    name: "The Empty Thought",
    difficulty: "easy",
    lines: [
      "'It' is there when you don't have anything,",
      "If you think of 'it', you can never think a thing.",
      "There is a reason for 'it', for why you can't think,",
      "As when you think of 'it', you actually never think.",
      "Let us stop thinking then, and go for its shape,",
      "Alas! 'it' has no shape or size, 'it' has nothing in 'it'.",
      "'It' makes this riddle so special that, this is no special anyhow,",
      "these are enough hints for you to guess, so find the 'it' now!",
    ],
    hints: ["It is the absence rather than the presence of something.", "The answer itself describes emptiness."],
    answer: "nothing",
    
  },
  {
    id: 8,
    name: "Something's Simple Here",
    difficulty: "easy",
    lines: [
      "'It' is the front of women, 'it' is at the back of cow,",
      "'It' is what that starts the world.",
      "If you see carefully, 'it' is made up of two 'V's,",
      "And is in warmth, not in the cold.",
      "You have seen 'it', the 'it' you have to guess,",
      "About which i'm talking in the first 4 lines.",
      "Believe this or not, the answer appeared,",
      "in the riddle itself, many times!",
    ],
    hints: [
      "Read the words literally rather than their meanings.",
      "It's not related to anythings said above, but their spellings.",
    ],
    answer: ["the letter w", "w", "the alphabet w"],
    
  },
  {
    id: 9,
    name: "One Word, Many Wings",
    difficulty: "tough",
    lines: [
      "'It' lives in a hive, flying from flower to flower,",
      "'It' is controlled by terrorists, or by military tower.",
      "'It' may have a battery, or maybe a heart like you,",
      "'It' might not sting you, but 'it' might shoot, it's true.",
      "'It' may also be person, who lives on work of others,",
      "Or 'it' could be irritating, a musical tone rather.",
      "This is interesting, for 'it' has many meanings,",
      "so 'it' could be found by a few,",
      "Now, guess the 'it', you have some time,",
      "till I make a riddle new.",
    ],
    hints: [
      "Every clue points to a different meaning of the same word.",
      "Think of insects, aircraft, music, and people, it's more commonly known as a controllable flying object though.",
    ],
    answer: "drone",
    
  },
  { 
    id: 10,
    name: "Run on it, Do it, Drive on it",
    difficulty: "tough",
    lines: [
      "'It' is a verb, 'it' is a noun,",
      "I run on 'it' , when 'it' is on ground.",
      "Police does 'it' , when a car is stolen,",
      "'It' is on which the stolen car is driven.",
      "'It' is the series of the songs on my PC,",
      "no doubt you can find 'it' , this one's too ez.",
    ],
    hints: [
      "The same word can mean to follow, a path, or an individual song.",
      "Railways are closely associated with one of its meanings.",
    ],
    answer: "track",
    
  },
  {
    id: 11,
    name: "I Thought it was Camel, but...",
    difficulty: "moderate",
    lines: [
      "'It' is brown, 'it' has a hump,",
      "'it' is an animal indeed,",
      "'It' has four legs, a quiet nature,",
      "and doesn't need a regular feed.",
      "BUT,",
      "'it' doesn't know, where 'it' is, and",
      "where is the family gone,",
      "and why is there no sand, but snow,",
      "and when did 'it' become all alone.",
      "For you, I tracked 'it', 'it' is at North Pole,",
      "far away, north of Rome,",
      "a camel lives in desert, and not at a pole,",
      "so, think again, guessing the 'it' is your goal.",
    ],
    hints: [
      "The answer is more specific than just the animal.",
      "The location described is completely wrong for where 'it' belongs.",
    ],
    answer: "lost camel",
    
  },
  {
    id: 12,
    name: "Which Number?",
    difficulty: "moderate",
    lines: [
      "When If I put all of these one by one then-",
      "'it' is the number of letters that complete writing 'ten',",
      "'it' is the number of books I can put in my empty bag,",
      "'it' is the number of files I can put on the vacant rack,",
      "'it' is the number of people that can sit on an unoccupied seat,",
      "'it'  is the number of words that I can write on a blank sheet,",
      "'it'  is the number of biscuits I can put in an empty glass,",
      "'it'  is the number of people who can own uninhabited villas,",
      "'it'  is the number of bricks that completes a building,",
      "'it'  is the number of words that completed this riddle writing.",
      "I really don't know why I would put, biscuits in a glass,",
      "Just ignore that nonsense, find the 'it' , real quick and fast.",
    ],
    hints: [
      "Every example depends on something being empty before the first addition.",
      "The answer relates to how adding that number of things not let the container be empty anymore.",
    ],
    answer: ["one", "1"],
    
  },
  {
    id: 13,
    name: "Rules and Contradictions",
    difficulty: "easy",
    lines: [
      "'It' is where success comes before work,",
      "'it' is where a chick comes before egg,",
      "If we open 'it' we can find nothing in 'it',",
      "yet 'it' has chicken and omelet and egg.",
      "'It' is in our Earth, but also, Earth is in 'it',",
      "'it' may get ruined by water, still has water in 'it'.",
      "'It' is not living but still, has emotion and brain,",
      "think and think, and find the thing, until you go insane!",
    ],
    hints: [
      "Some specific order explains several of the clues.",
      "It contains countless words without physically containing the things they describe.",
    ],
    answer: "dictionary",
    
  },
  {
    id: 14,
    name: "Dinner Guest",
    difficulty: "tough",
    lines: [
      "On the dining table, you may dine on 'it',",
      "'it' should be sour, if in your mouth 'it' could fit.",
      "But in real 'it' would eat you in a blink,",
      "if 'it' was present, what is 'it'? you think...",
    ],
    hints: [
      "The riddle is kinda a joke, so better you don't think it's edible, neither is it sour (or maybe it is, who knows).",
      "The joke depends on a phrase sounding like a single word.",
    ],
    answer: ["dine-a-sour", "dinosaur"],
    
  },
  {
    id: 15,
    name: "Layers of Tears",
    difficulty: "easy",
    lines: [
      "'It' makes us cry, so 'it' might be emotional,",
      "'It' goes on and on, and has eye in the middle,",
      "Find the 'it', I accept, this riddle is not original.",
    ],
    hints: ["The 'eye' is part of its spelling, not its anatomy.", "Peeling 'it' is enough to make many people cry."],
    answer: "onion",
    
  },
  {
    id: 16,
    name: "Life on a Keypad",
    difficulty: "moderate",
    lines: [
      "If 1 is a foetus, who has never taken in air,",
      "and if 2 is a baby, who needs a lot of care;",
      "if 3 is a child, who without candy goes wild,",
      "and if 6 is a teenager, who isn't anymore a child;",
      "if 7 is an adult, working for wealth to prosper,",
      "and if 8 is an old man, who can't listen to a whisper;",
      "if 9 is a skeleton, as after death is no one alive,",
      "then you've to find the 'it', if 'it' is four and five.",
    ],
    hints: [
      "Imagine the digits representing stages of a person's life, but the answer got nothing to do with 'it'.",
      "The answer is formed by combining two consecutive digits.",
    ],
    answer: ["nine", "9"],
    
  },
  {
    id: 17,
    name: "The Timeless Guard",
    difficulty: "easy",
    lines: [
      "While walking in the nature, I ended up in a city,",
      "Markets were closed, doors were shut, just a person asking for pity.",
      "I asked what he wanted, he said - I want 'it',",
      "Pointing towards an animal, under the shed, lamplit.",
      "'It' is a watch that shows no time,",
      "And sits there all silent and aloof,",
      "The man wants 'it' for protection, guess the 'it',",
      "'It' is still under the shed, in the cold night, oof !",
    ],
    hints: ["Split the word into two familiar English words.", "Its job is to keep watch, not to tell time."],
    answer: "watchdog",
    
  },
  {
    id: 18,
    name: "Crossbreeding I",
    difficulty: "tough",
    lines: [
      "I just learned the process of crossbreeding and,",
      "crossed my shining Ferrari with my dearest kitty cat,",
      "'it' is soft like my pet, and stylish like my car,",
      "guess the 'it' till I find something to cross with a rat.",
    ],
    hints: ["You probably have one somewhere in your house.", "Blend the names of the two things together."],
    answer: "carpet",
    
  },
  {
    id: 19,
    name: "Always Said Wrong",
    difficulty: "easy",
    lines: [
      "No matter how easy the situation is,",
      "you'll always tell 'it' incorrect,",
      "no doubt you are a fool because,",
      "you'll never speak 'it' correct.",
      "You aren't a good person,",
      "as you use 'it' for wrong,",
      "'it' isn't rare, easily find 'it',",
      "no need to think for long.",
    ],
    hints: ["Pronouncing it correctly still means you've said it.", "The joke is about saying the word itself."],
    answer: "incorrect",
    
  },
  {
    id: 20,
    name: "Everything here is...",
    difficulty: "easy",
    lines: [
      "The Earth was never round firstly,",
      "and the space is filled with air,",
      "aliens pull us down and not some force,",
      "which you all call gravity, but don't fear.",
      "Fruits were never meant to be eaten,",
      "that's a mistake everyone has made,",
      "they are gods who are evil, not the demons,",
      "and the thieves do never invade.",
      "Guess the 'it', oh I do agree that,",
      "in the riddle 'it' never appear,",
      "then let me use 'it' in the last line-",
      "the facts in the riddle were all 'it', now 'it' is clear.",
    ],
    hints: [
      "Every statement before the ending shares the same quality.",
      "The final line directly describes every previous claim.",
    ],
    answer: ["wrong", "misconceptions", "incorrect", "untrue", "myth", "inaccurate", "faulty"],
    
  },
  {
    id: 901,
    name: "Riddle Domain: Lighting Up",
    difficulty: "master",
    lines: [
      "You went to the domain of riddles,",
      "your task now is to think up a sequence,",
      "on the dark wall there is, a mark \"three\",",
      "above the picture of Nightingale Florence.",
      "You are provided with some set of rules,",
      "on a paper which is wrinkly and crinkly,",
      "paper is not to be burnt at the last,",
      "so make sure, the rules, you carefully see.",
      "",
      "RULES (as on the crinkly-wrinkly paper)",
      "",
      "1. Those that are meant, to shine using wire,",
      "light them just after putting, something on fire.",
      "",
      "2. Those that produce, too much of sound,",
      "light them before the paper, that too on ground.",
      "",
      "3. The first two you have to light, the ones that gets used,",
      "you have to burn them, they'll finish, don't get confused.",
      "",
      "4. Also, burn the firecracker, only using the candle,",
      "take care you don't get hurt, or burn up your sandal.",
      "",
      "Suddenly and magically, in front of you appears,",
      "a short white 'candle' and a noisemaker 'cracker',",
      "and an electric 'lamp' and a 900w 'bulb',",
      "yes really! That is written on the wrapper.",
      "Also, you got all the tools to light,",
      "like the wires, the switches and powerful battery,",
      "just find the correct sequence, and light up,",
      "and walk away with the treasure for free.",
      "",
      "What is 'it' that you will light up first?",
      "Find the 'it' before the domain god gives you curse."
    ],
    hints: ["Use pen and paper and arrange the things- candle, cracker, lamp, bulb, paper in correct order.", "Are you sure you'd burn one of these first?"],
    answer: ["lighter","matches","match"]
  },
  {
    id: 21,
    name: "The Bus You Can't Ride",
    difficulty: "easy",
    lines: [
      "Find the 'it', if 'it' is a bus which you can't ride,",
      "if huge, 'it' is a stress, which you would never like,",
      "you want 'it' early, so that you can prepare,",
      "you want 'it' for large numbers, about which you all care.",
    ],
    hints: ["The first line is a wordplay, not an actual vehicle.", "Students often ask for 'it' before exams."],
    answer: "syllabus",
    
  },
  {
    id: 22,
    name: "The Dry Ocean",
    difficulty: "moderate",
    lines: [
      "'It' is just an ocean, but without any water,",
      "so, there are no sharks or fishes, there is no slaughter.",
      "There is no land, don't ask me why, because-",
      "'it' is JUST an ocean, but without any water.",
      "'It' has no markings, so 'it' is not a map,",
      "'it' is not a planet, which only has gas,",
      "you may call 'it' like a riddle, without any words,",
      "or maybe like a tree with nests, without any birds.",
      "'It' has no ships sailing, no waves, no motion,",
      "what is 'it' that has no water, yet is called an ocean?",
    ],
    hints: ["Take the description completely literally.", "The answer is exactly what the riddle keeps describing!"],
    answer: "an ocean without water",
    
  },
  {
    id: 23,
    name: "Black to Red",
    difficulty: "easy",
    lines: [
      "I bought 'it', I got 'it', from somewhere, somehow,",
      "'it' was black like the dreary but scary night, but now,",
      "'it' is red on use, find the 'it', if in the day,",
      "I would throw 'it', when 'it' will become boring gray.",
    ],
    hints: ["Think about what changes color on usage and after it.", "The usage here might refer to burning it."],
    answer: ["coal", "charcoal"],
  },
  {
    id: 24,
    name: "The Wet Coat",
    difficulty: "moderate",
    lines: [
      "'It' is a coat that is wore wet,",
      "not by you but by houses and machines,",
      "'it' is no cloth, 'it' has no buttons,",
      "just a colour, so find 'it' by any means.",
    ],
    hints: ["The 'coat' isn't clothing.", "Walls and vehicles often receive one for protection and appearance."],
    answer: "coat of paint",
    
  },
  {
    id: 25,
    name: "The Weeping Sky",
    difficulty: "easy",
    lines: [
      "'It' cries so that, you are able to live,",
      "'it' flies without any wings.",
      "If 'it' is grey, you may hear 'it'",
      "though 'it' neither speaks nor sings.",
      "'It''s arrival can even defeat the bright,",
      "warm shine of the days or the noon,",
      "Guess the 'it', answer and wait,",
      "the next one is coming soon!",
    ],
    hints: ["Its tears are essential for you, and in fact everyone", "A darker one often arrives with thunder."],
    answer: "clouds",
    
  },
  {
    id: 26,
    name: "The Swift Messenger",
    difficulty: "easy",
    lines: [
      "If 'it' is the first from the center then,",
      "you will be on the third,",
      "'It' moved through the worlds, a god with speed,",
      "by flying like a bird.",
      "A drop of 'it' maybe a death for you,",
      "What is 'it', a guess can you do?",
    ],
    hints: [
      "In another meaning, 'it' is toxic and is first in some arrangement.",
      "The same name belongs to both a Roman god and a planet.",
    ],
    answer: "mercury",
    
  },
  {
    id: 27,
    name: "Seen From Every Angle",
    difficulty: "tough",
    lines: [
      "'It' looks like some kind of 'T',",
      "-says person when he sees 'it' from far & open,",
      "No ! 'It' is more like a circle,",
      "-says the brightshining mighty sun.",
      "Hold 'it' straight and, 'it' is a 'one' when closed,",
      "-says the same little fellow person,",
      "Interrupts the mannerless sun again,",
      "'it' is a dot and not a one.",
      "Whatever 'it' looks like, 'it' is always the same,",
      "what matters is that, you have to find its name.",
    ],
    hints: [
      "Its appearance changes depending on how it's held.",
      "You'd be glad to have one if it suddenly started raining.",
    ],
    answer: "umbrella",
    
  },
  {
    id: 28,
    name: "The Working Weight",
    difficulty: "tough",
    lines: [
      "'It' is professional weight unit by name,",
      "'it' works, 'it' runs, and still has no brain.",
      "'it' has no legs, no hands, no seed,",
      "'it' may work on snakes, or letters 'it' may read.",
      "'it' won't work, even with the slightest of fault,",
      "let your guesses come out, without any hault !",
    ],
    hints: [
      "professional weight unit, or maybe a unit of weight which is somehow pro?",
      "Computers execute 'it' line by line.",
    ],
    answer: "program",
    
  },
  {
    id: 29,
    name: "Changing on Seeing More",
    difficulty: "moderate",
    lines: [
      "If first two are seen, then 'it' is a he,",
      "If first three, then 'it' is her,",
      "If the first four are seen, 'it' has someone,",
      "who is good n great and a winner.",
      "Leave the numbers, and go for the whole,",
      "'it' describes a women of good-n-great soul,",
      "whether admired for beauty or some work real good,",
      "finding the 'it' is what all you should.",
    ],
    hints: [
      "Start writing the letters as the riddles say maybe.",
      "The complete word is commonly used for a female lead in stories.",
    ],
    answer: "heroine",
    
  },
  {
    id: 30,
    name: "Story of the Stone",
    difficulty: "easy",
    lines: [
      "I got a stone from a person, who was then a chancellor,",
      "then I kept 'it' on the stage, for the geologist dancer.",
      "The dancer told me about 'it', 'it' was from tropic of cancer,",
      "what is 'it' now, after, listening to the dancer's answer ?",
    ],
    hints: [
      "Its owner, location, and information about 'it' are irrelevant.",
      "Nothing described changes the object itself.",
    ],
    answer: "stone",
    
  },
  {
    id: 31,
    name: "The Silent Messenger",
    difficulty: "moderate",
    lines: [
      "From your houses to the offices,",
      "along the roads and highway 'it' runs,",
      "without any legs 'it' travels miles,",
      "whether 'it' rains or is below the sun.",
      "Not some vehicle, 'it' is not some field,",
      "though some say 'it' travels from pole to pole,",
      "'it' delivers your words, your feelings and all,",
      "For now, finding the 'it' is your only goal.",
    ],
    hints: ["'It' carries conversations, not passengers.", "Think of the physical connection rather than a device."],
    answer: ["telephone wire", "telephone line", "communication cable"],
    
  },
  {
    id: 32,
    name: "Climbing Without Moving",
    difficulty: "easy",
    lines: [
      "'It' is made of blocks, or lines one or few,",
      "'it' may show heart rate, performance or time,",
      "'it' stays at one place, while climbing up-n-down,",
      "ignore this sentence as I had nothing to rhyme.",
      "'It' has a scale, and has markings on 'it',",
      "'it' can be related with votes or cars or dresses,",
      "If made for long, 'it' is long, that's obvious,",
      "so now this one is done, do you have any guesses ?",
    ],
    hints: ["'It' visually represents information.", "Bar, line, and pie are common varieties."],
    answer: "graph",
    
  },
  {
    id: 33,
    name: "Friend and Foe",
    difficulty: "moderate",
    lines: [
      "In cold 'it' makes you ill if,",
      "for long 'it' is on you,",
      "if you think 'it' is harmful then, beware!",
      "'it' is already inside you too.",
      "If 'it' surrounds you for quite some time,",
      "you would have to die,",
      "If 'it's' not around you for hours,",
      "you might have to cry.",
      "'It' is in your kitchen,",
      "in the soil and in the air,",
      "finding the 'it' is-",
      "neither hard, nor 'it' is rare.",
    ],
    hints: ["Too much or too little of it can both be dangerous.", "Your body is largely made of it."],
    answer: "water",
    
  },
  {
    id: 34,
    name: "Alike Friend",
    difficulty: "easy",
    lines: [
      "'It' may be alike, but is not as brave as me,",
      "'it' fears the bright, or maybe shy as you may see.",
      "'It' is ahead of me, when I move towards the dark,",
      "I went with 'it' in the muddy lands, but 'it' came without a mark.",
      "What is the 'it' having two hands and a head,",
      "'it' needs no water to live, or perhaps 'it' is dead.",
    ],

    hints: [
      "Try to touch it, nah you can't.",
      "Its behavior changes depending on where the light comes from.",
    ],
    answer: "shadow",
    
  },
  {
    id: 35,
    name: "Crossbreeding II",
    difficulty: "tough",
    lines: [
      "I finally made 'it' by crossing a rat,",
      "with my research of a hundred years.",
      "I crossed the thing found in salt and tap water,",
      "the thing that a diamond never bears.",
      "'It' was edible, but there was no one hungry,",
      "so I crossed with 'it' some gems too,",
      "now 'it' should live and change by time,",
      "guess the 'it', you have got every clue.",
    ],

    hints: [
      "The answer is created step by step rather than being found directly.",
      "Several clues point toward science, but they don't all belong to the same field.",
    ],
    answer: ["gene-rat-ion","generation"],
    
  },
  {
    id: 902,
    name: "Riddle Domain: Markings and Doors",
    difficulty: "master",
    lines: [
      "You are once again in the domain of riddles,",
      "your task now is to exit from the correct gate;",
      "Octagonal room with a door at each wall there is,",
      "you'll get a curse if you chose wrong or choose late.",
      "Every door has a mark, of a circle, square or triangle,",
      "and above them are eyes either closed or open;",
      "Suddenly all marks disappear, and again, crinkly-wrinkly appears,",
      "the paper will help you, till the escape is done.",
      "",
      "INFO (as on the crinkly-wrinkly paper)-",
      "",
      "1. There are three open eyes, one for each shape on the doors,",
      "entry and exit are identical, behind which there are no deadly boars.",
      "",
      "2. Number of squares and circles are equal, and four closed eyes are in row,",
      "strange sounds come from opened-eyed doors, due to the high volt current flow.",
      "",
      "3. When numbering from square with eye not shut, and second with eye open,",
      "the 4th & 5th doors have circles on them, where one of the eye is open.",
      "",
      "4. The triangles are on same position from ends, and the no.6 is square,",
      "also the last three eyes above doors are closed, opposite to centres- lie the squares.",
      "",
      "If entry is different,",
      "from neighbours by shape,",
      "which is 'it' from which you'll",
      "loot treasure and escape?",
      "",
      "",
      "Note: Answer by door number, shape and eye, like- 4 square open",
    ],
    hints: ["Use pen and paper and arrange the markings on doors.", "1st door is square close, also in orthogonal room, 4th distance doors are opposites, interpret other hints similarly."],
    answer: ["8 square close","eight square close","8 square closed","8th square closed eye"]
  },
]
